// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvybbjfskvikawpnfhsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2eWJiamZza3Zpa2F3cG5maHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzIzMjcsImV4cCI6MjA2MzcwODMyN30.pKkBE6hQCQNRS_Xen1MMu8zRm6-8n-gMpLUGdpPZYjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);